### ISSUE TITLE
Fehlender Quellcode

### ISSUE THREAD

**Issue by lfuelling** [SelfGamer/Karorennen#1]
Yo,

kann's sein, dass ein bisschen was von eurem Code fehlt?

Ich würde mir gern mal die Kollisionserkennung und die KI anschauen.

LG

Lukas (der typ mit den dreads)

**Comment by SelfGamer** [comment]
Whoa ups... Beim Hochladen heute Morgen ist wohl was schiefgelaufen. Ich korrigiere das mal.

**Comment by lfuelling** [comment]
Sehr cool, danke 👾
